export { applyPreset, presetRegistry } from "./registry";
export { brutalistPreset } from "./brutalist";
export { corporatePreset } from "./corporate";
export { defaultPreset } from "./default";
export { iosPreset } from "./ios";
export { macosPreset } from "./macos";
export { minimalPreset } from "./minimal";
export { modernPreset } from "./modern";
export { neonPreset } from "./neon";
export { retroPreset } from "./retro";
export type { PresetName, PresetRegistry } from "./types";
